// ---------------------------------------------------------------------------
// GENERATED FILE - DO NOT EDIT BY HAND.
// Source: vendor/provider-openapi.json (provider OpenAPI 1.0)
// Regenerate: npm run gen:provider
//
// 98 operations across 48 paths.
// ---------------------------------------------------------------------------

export interface ProviderQueryParam {
  name: string;
  required: boolean;
  type: string;
}

export interface ProviderOperation {
  operationId: string;
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
  tag: string;
  summary: string;
  pathParams: string[];
  queryParams: ProviderQueryParam[];
  hasBody: boolean;
  isMultipart: boolean;
  /** Responds 302 to a short-lived presigned URL instead of a JSON body. */
  isRedirect: boolean;
}

export const PROVIDER_OPERATION_COUNT = 98;

export const PROVIDER_OPERATIONS: readonly ProviderOperation[] = [
  {
    operationId: "AnalyticsController_query",
    method: "POST",
    path: "/analytics",
    tag: "Analytics",
    summary: "Create Analytics Queries",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "AssistantController_findAll",
    method: "GET",
    path: "/assistant",
    tag: "Assistants",
    summary: "List Assistants",
    pathParams: [],
    queryParams: [{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "AssistantController_create",
    method: "POST",
    path: "/assistant",
    tag: "Assistants",
    summary: "Create Assistant",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "AssistantController_findOne",
    method: "GET",
    path: "/assistant/{id}",
    tag: "Assistants",
    summary: "Get Assistant",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "AssistantController_update",
    method: "PATCH",
    path: "/assistant/{id}",
    tag: "Assistants",
    summary: "Update Assistant",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "AssistantController_remove",
    method: "DELETE",
    path: "/assistant/{id}",
    tag: "Assistants",
    summary: "Delete Assistant",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallController_findAll",
    method: "GET",
    path: "/call",
    tag: "Calls",
    summary: "List Calls",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"assistantId","required":false,"type":"string"},{"name":"phoneNumberId","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallController_create",
    method: "POST",
    path: "/call",
    tag: "Calls",
    summary: "Create Call",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallController_findOne",
    method: "GET",
    path: "/call/{id}",
    tag: "Calls",
    summary: "Get Call",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallController_update",
    method: "PATCH",
    path: "/call/{id}",
    tag: "Calls",
    summary: "Update Call",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallController_deleteCallData",
    method: "DELETE",
    path: "/call/{id}",
    tag: "Calls",
    summary: "Delete Call",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallArtifactController_assistantRecordingDownload",
    method: "GET",
    path: "/call/{id}/assistant-recording",
    tag: "Calls",
    summary: "Download Call Assistant Recording",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CallArtifactController_callLogsDownload",
    method: "GET",
    path: "/call/{id}/call-logs",
    tag: "Calls",
    summary: "Download Call Logs",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CallArtifactController_customerRecordingDownload",
    method: "GET",
    path: "/call/{id}/customer-recording",
    tag: "Calls",
    summary: "Download Call Customer Recording",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CallArtifactController_monoRecordingDownload",
    method: "GET",
    path: "/call/{id}/mono-recording",
    tag: "Calls",
    summary: "Download Call Mono Recording",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CallArtifactController_pcapDownload",
    method: "GET",
    path: "/call/{id}/pcap",
    tag: "Calls",
    summary: "Download Call Packet Capture (pcap)",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CallArtifactController_stereoRecordingDownload",
    method: "GET",
    path: "/call/{id}/stereo-recording",
    tag: "Calls",
    summary: "Download Call Stereo Recording",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CallArtifactController_videoRecordingDownload",
    method: "GET",
    path: "/call/{id}/video-recording",
    tag: "Calls",
    summary: "Download Call Video Recording",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: true,
  },
  {
    operationId: "CampaignController_findAll",
    method: "GET",
    path: "/campaign",
    tag: "Campaigns",
    summary: "List Campaigns",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"status","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_create",
    method: "POST",
    path: "/campaign",
    tag: "Campaigns",
    summary: "Create Campaign",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_findOne",
    method: "GET",
    path: "/campaign/{id}",
    tag: "Campaigns",
    summary: "Get Campaign",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_update",
    method: "PATCH",
    path: "/campaign/{id}",
    tag: "Campaigns",
    summary: "Update Campaign",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_remove",
    method: "DELETE",
    path: "/campaign/{id}",
    tag: "Campaigns",
    summary: "Delete Campaign",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ChatController_listChats",
    method: "GET",
    path: "/chat",
    tag: "Chats",
    summary: "List Chats",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"assistantId","required":false,"type":"string"},{"name":"assistantIdAny","required":false,"type":"string"},{"name":"squadId","required":false,"type":"string"},{"name":"sessionId","required":false,"type":"string"},{"name":"previousChatId","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ChatController_createChat",
    method: "POST",
    path: "/chat",
    tag: "Chats",
    summary: "Create Chat",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ChatController_getChat",
    method: "GET",
    path: "/chat/{id}",
    tag: "Chats",
    summary: "Get Chat",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ChatController_deleteChat",
    method: "DELETE",
    path: "/chat/{id}",
    tag: "Chats",
    summary: "Delete Chat",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ChatController_createOpenAIChat",
    method: "POST",
    path: "/chat/responses",
    tag: "Chats",
    summary: "Create Chat (OpenAI Compatible)",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_getPaginated",
    method: "GET",
    path: "/eval",
    tag: "Eval",
    summary: "List Evals",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_create",
    method: "POST",
    path: "/eval",
    tag: "Eval",
    summary: "Create Eval",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_get",
    method: "GET",
    path: "/eval/{id}",
    tag: "Eval",
    summary: "Get Eval",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_update",
    method: "PATCH",
    path: "/eval/{id}",
    tag: "Eval",
    summary: "Update Eval",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_remove",
    method: "DELETE",
    path: "/eval/{id}",
    tag: "Eval",
    summary: "Delete Eval",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_getRunsPaginated",
    method: "GET",
    path: "/eval/run",
    tag: "Eval",
    summary: "List Eval Runs",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_run",
    method: "POST",
    path: "/eval/run",
    tag: "Eval",
    summary: "Create Eval Run",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_getRun",
    method: "GET",
    path: "/eval/run/{id}",
    tag: "Eval",
    summary: "Get Eval Run",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "EvalController_removeRun",
    method: "DELETE",
    path: "/eval/run/{id}",
    tag: "Eval",
    summary: "Delete Eval Run",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "FileController_findAll",
    method: "GET",
    path: "/file",
    tag: "Files",
    summary: "List Files",
    pathParams: [],
    queryParams: [{"name":"purpose","required":true,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "FileController_create",
    method: "POST",
    path: "/file",
    tag: "Files",
    summary: "Upload File",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: true,
    isRedirect: false,
  },
  {
    operationId: "FileController_findOne",
    method: "GET",
    path: "/file/{id}",
    tag: "Files",
    summary: "Get File",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "FileController_update",
    method: "PATCH",
    path: "/file/{id}",
    tag: "Files",
    summary: "Update File",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "FileController_remove",
    method: "DELETE",
    path: "/file/{id}",
    tag: "Files",
    summary: "Delete File",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ScorecardController_getPaginated",
    method: "GET",
    path: "/observability/scorecard",
    tag: "Observability/Scorecard",
    summary: "List Scorecards",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ScorecardController_create",
    method: "POST",
    path: "/observability/scorecard",
    tag: "Observability/Scorecard",
    summary: "Create Scorecard",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ScorecardController_get",
    method: "GET",
    path: "/observability/scorecard/{id}",
    tag: "Observability/Scorecard",
    summary: "Get Scorecard",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ScorecardController_update",
    method: "PATCH",
    path: "/observability/scorecard/{id}",
    tag: "Observability/Scorecard",
    summary: "Update Scorecard",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ScorecardController_remove",
    method: "DELETE",
    path: "/observability/scorecard/{id}",
    tag: "Observability/Scorecard",
    summary: "Delete Scorecard",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "PhoneNumberController_findAll",
    method: "GET",
    path: "/phone-number",
    tag: "Phone Numbers",
    summary: "List Phone Numbers",
    pathParams: [],
    queryParams: [{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "PhoneNumberController_create",
    method: "POST",
    path: "/phone-number",
    tag: "Phone Numbers",
    summary: "Create Phone Number",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "PhoneNumberController_findOne",
    method: "GET",
    path: "/phone-number/{id}",
    tag: "Phone Numbers",
    summary: "Get Phone Number",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "PhoneNumberController_update",
    method: "PATCH",
    path: "/phone-number/{id}",
    tag: "Phone Numbers",
    summary: "Update Phone Number",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "PhoneNumberController_remove",
    method: "DELETE",
    path: "/phone-number/{id}",
    tag: "Phone Numbers",
    summary: "Delete Phone Number",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ProviderResourceController_getProviderResourcesPaginated",
    method: "GET",
    path: "/provider/{provider}/{resourceName}",
    tag: "Provider Resources",
    summary: "List Provider Resources",
    pathParams: ["provider","resourceName"],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"resourceId","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ProviderResourceController_createProviderResource",
    method: "POST",
    path: "/provider/{provider}/{resourceName}",
    tag: "Provider Resources",
    summary: "Create Provider Resource",
    pathParams: ["provider","resourceName"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ProviderResourceController_getProviderResource",
    method: "GET",
    path: "/provider/{provider}/{resourceName}/{id}",
    tag: "Provider Resources",
    summary: "Get Provider Resource",
    pathParams: ["provider","resourceName","id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ProviderResourceController_updateProviderResource",
    method: "PATCH",
    path: "/provider/{provider}/{resourceName}/{id}",
    tag: "Provider Resources",
    summary: "Update Provider Resource",
    pathParams: ["provider","resourceName","id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ProviderResourceController_deleteProviderResource",
    method: "DELETE",
    path: "/provider/{provider}/{resourceName}/{id}",
    tag: "Provider Resources",
    summary: "Delete Provider Resource",
    pathParams: ["provider","resourceName","id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "BoardController_findAll",
    method: "GET",
    path: "/reporting/board",
    tag: "Board",
    summary: "Get Boards",
    pathParams: [],
    queryParams: [{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "BoardController_create",
    method: "POST",
    path: "/reporting/board",
    tag: "Board",
    summary: "Create Board",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "BoardController_findOne",
    method: "GET",
    path: "/reporting/board/{id}",
    tag: "Board",
    summary: "Get Board",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "BoardController_update",
    method: "PATCH",
    path: "/reporting/board/{id}",
    tag: "Board",
    summary: "Update Board",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "BoardController_remove",
    method: "DELETE",
    path: "/reporting/board/{id}",
    tag: "Board",
    summary: "Delete Board",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "BoardController_metricsOverviewEnsure",
    method: "GET",
    path: "/reporting/board/default/metrics-overview",
    tag: "Board",
    summary: "Get Default Metrics Overview Board",
    pathParams: [],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_findAll",
    method: "GET",
    path: "/reporting/insight",
    tag: "Insight",
    summary: "Get Insights",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_create",
    method: "POST",
    path: "/reporting/insight",
    tag: "Insight",
    summary: "Create Insight",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_findOne",
    method: "GET",
    path: "/reporting/insight/{id}",
    tag: "Insight",
    summary: "Get Insight",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_update",
    method: "PATCH",
    path: "/reporting/insight/{id}",
    tag: "Insight",
    summary: "Update Insight",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_remove",
    method: "DELETE",
    path: "/reporting/insight/{id}",
    tag: "Insight",
    summary: "Delete Insight",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_run",
    method: "POST",
    path: "/reporting/insight/{id}/run",
    tag: "Insight",
    summary: "Run Insight",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "InsightController_preview",
    method: "POST",
    path: "/reporting/insight/preview",
    tag: "Insight",
    summary: "Preview Insight",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SessionController_findAllPaginated",
    method: "GET",
    path: "/session",
    tag: "Sessions",
    summary: "List Sessions",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"name","required":false,"type":"string"},{"name":"assistantId","required":false,"type":"string"},{"name":"assistantIdAny","required":false,"type":"string"},{"name":"squadId","required":false,"type":"string"},{"name":"workflowId","required":false,"type":"string"},{"name":"numberE164CheckEnabled","required":false,"type":"boolean"},{"name":"extension","required":false,"type":"string"},{"name":"assistantOverrides","required":false,"type":"string"},{"name":"squadOverrides","required":false,"type":"string"},{"name":"number","required":false,"type":"string"},{"name":"sipUri","required":false,"type":"string"},{"name":"name","required":false,"type":"string"},{"name":"email","required":false,"type":"string"},{"name":"externalId","required":false,"type":"string"},{"name":"customerNumberAny","required":false,"type":"string"},{"name":"phoneNumberId","required":false,"type":"string"},{"name":"phoneNumberIdAny","required":false,"type":"array"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SessionController_create",
    method: "POST",
    path: "/session",
    tag: "Sessions",
    summary: "Create Session",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SessionController_findOne",
    method: "GET",
    path: "/session/{id}",
    tag: "Sessions",
    summary: "Get Session",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SessionController_update",
    method: "PATCH",
    path: "/session/{id}",
    tag: "Sessions",
    summary: "Update Session",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SessionController_remove",
    method: "DELETE",
    path: "/session/{id}",
    tag: "Sessions",
    summary: "Delete Session",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SquadController_findAll",
    method: "GET",
    path: "/squad",
    tag: "Squads",
    summary: "List Squads",
    pathParams: [],
    queryParams: [{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SquadController_create",
    method: "POST",
    path: "/squad",
    tag: "Squads",
    summary: "Create Squad",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SquadController_findOne",
    method: "GET",
    path: "/squad/{id}",
    tag: "Squads",
    summary: "Get Squad",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SquadController_update",
    method: "PATCH",
    path: "/squad/{id}",
    tag: "Squads",
    summary: "Update Squad",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "SquadController_remove",
    method: "DELETE",
    path: "/squad/{id}",
    tag: "Squads",
    summary: "Delete Squad",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "StructuredOutputController_findAll",
    method: "GET",
    path: "/structured-output",
    tag: "Structured Outputs",
    summary: "List Structured Outputs",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"name","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "StructuredOutputController_create",
    method: "POST",
    path: "/structured-output",
    tag: "Structured Outputs",
    summary: "Create Structured Output",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "StructuredOutputController_findOne",
    method: "GET",
    path: "/structured-output/{id}",
    tag: "Structured Outputs",
    summary: "Get Structured Output",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "StructuredOutputController_update",
    method: "PATCH",
    path: "/structured-output/{id}",
    tag: "Structured Outputs",
    summary: "Update Structured Output",
    pathParams: ["id"],
    queryParams: [{"name":"schemaOverride","required":true,"type":"string"}],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "StructuredOutputController_remove",
    method: "DELETE",
    path: "/structured-output/{id}",
    tag: "Structured Outputs",
    summary: "Delete Structured Output",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "StructuredOutputController_run",
    method: "POST",
    path: "/structured-output/run",
    tag: "Structured Outputs",
    summary: "Run Structured Output",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ToolController_findAll",
    method: "GET",
    path: "/tool",
    tag: "Tools",
    summary: "List Tools",
    pathParams: [],
    queryParams: [{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ToolController_create",
    method: "POST",
    path: "/tool",
    tag: "Tools",
    summary: "Create Tool",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ToolController_findOne",
    method: "GET",
    path: "/tool/{id}",
    tag: "Tools",
    summary: "Get Tool",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ToolController_update",
    method: "PATCH",
    path: "/tool/{id}",
    tag: "Tools",
    summary: "Update Tool",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "ToolController_remove",
    method: "DELETE",
    path: "/tool/{id}",
    tag: "Tools",
    summary: "Delete Tool",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_findAllV2",
    method: "GET",
    path: "/v2/campaign",
    tag: "Campaigns",
    summary: "List Campaigns V2",
    pathParams: [],
    queryParams: [{"name":"id","required":false,"type":"string"},{"name":"status","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_createV2",
    method: "POST",
    path: "/v2/campaign",
    tag: "Campaigns",
    summary: "Create Campaign V2",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_findOneV2",
    method: "GET",
    path: "/v2/campaign/{id}",
    tag: "Campaigns",
    summary: "Get Campaign V2",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_updateV2",
    method: "PATCH",
    path: "/v2/campaign/{id}",
    tag: "Campaigns",
    summary: "Update Campaign",
    pathParams: ["id"],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CampaignController_removeV2",
    method: "DELETE",
    path: "/v2/campaign/{id}",
    tag: "Campaigns",
    summary: "Delete Campaign",
    pathParams: ["id"],
    queryParams: [],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "PhoneNumberController_findAllPaginated",
    method: "GET",
    path: "/v2/phone-number",
    tag: "Phone Numbers",
    summary: "List Phone Numbers",
    pathParams: [],
    queryParams: [{"name":"search","required":false,"type":"string"},{"name":"page","required":false,"type":"number"},{"name":"sortOrder","required":false,"type":"string"},{"name":"sortBy","required":false,"type":"string"},{"name":"limit","required":false,"type":"number"},{"name":"createdAtGt","required":false,"type":"string"},{"name":"createdAtLt","required":false,"type":"string"},{"name":"createdAtGe","required":false,"type":"string"},{"name":"createdAtLe","required":false,"type":"string"},{"name":"updatedAtGt","required":false,"type":"string"},{"name":"updatedAtLt","required":false,"type":"string"},{"name":"updatedAtGe","required":false,"type":"string"},{"name":"updatedAtLe","required":false,"type":"string"}],
    hasBody: false,
    isMultipart: false,
    isRedirect: false,
  },
  {
    operationId: "CallController_createWebCall",
    method: "POST",
    path: "/call/web",
    tag: "Calls",
    summary: "Create Web Call",
    pathParams: [],
    queryParams: [],
    hasBody: true,
    isMultipart: false,
    isRedirect: false,
  },
] as const;

/** Compiled matchers, longest path first so /call/{id}/pcap beats /call/{id}. */
export const PROVIDER_OPERATION_MATCHERS: ReadonlyArray<{
  endpoint: ProviderOperation;
  regex: RegExp;
}> = PROVIDER_OPERATIONS.map((endpoint) => ({
  endpoint,
  regex: new RegExp(
    '^' + endpoint.path.replace(/\{[^}]+\}/g, '([^/]+)') + '$',
  ),
})).sort((a, b) => b.endpoint.path.length - a.endpoint.path.length);

/**
 * Resolves an inbound passthrough request to the provider operation it targets.
 * Returns null when no operation matches - the passthrough refuses unknown
 * paths rather than blindly forwarding them.
 */
export function matchProviderOperation(
  method: string,
  pathname: string,
): { endpoint: ProviderOperation; params: Record<string, string> } | null {
  const upper = method.toUpperCase();
  for (const { endpoint, regex } of PROVIDER_OPERATION_MATCHERS) {
    if (endpoint.method !== upper) continue;
    const match = regex.exec(pathname);
    if (!match) continue;
    const params: Record<string, string> = {};
    endpoint.pathParams.forEach((name, i) => {
      params[name] = decodeURIComponent(match[i + 1]);
    });
    return { endpoint, params };
  }
  return null;
}
